### ISSUE TITLE
Upgrade database schema too

### ISSUE THREAD

**Issue by foxycode** [stefansl/pma-updatescript#16]
It would be very nice if `phpmyadmin` database was updated too, otherwise all features doesn't work after upgrade of major version.

In any case, great work. Thanks you very much.

**Comment by stefansl** [comment]
Good point and I thought about it. It's not done with updating DB - in most cases you have to edit the config with values the script maybe does not know. So in my opinion this should be done by the admin.

**Comment by foxycode** [comment]
I believe you have all needed info in MyAdmin config. Problem could be adding new table entries, which are commented on sample conf. I'm not too friendly with bash as you seem to be, but I'm glad to help.

My idea:
- Check if phpMyAdmin settings is present and not commented in `config.inc.php`
- Compare versions and check that update sql file is present in installation
- Check `config.sample.inc.php`, parse missing table definitions and add them to `cinfig.inc.php`

Do you think this could work?

**Comment by stefansl** [comment]
This could work, but it could easily result in errors, I guess.

**Comment by foxycode** [comment]
You initial script can easily result in error too :) There is lot what needs to be checked. Question is, are you interested in adding schema update to you script?
